Models/EnumStatusTarefa.cs
namespace TrilhaApiDesafio.Models
{
    public enum EnumStatusTarefa
    {
        Pendente,
        Finalizado
    }
}

Models/ErrorViewModel.cs
namespace TrilhaApiDesafio.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TrilhaApiDesafio.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public EnumStatusTarefa Status { get; set; }

        public void ToggleStatus()
        {
            if(Status == EnumStatusTarefa.Pendente)
            {
                Status = EnumStatusTarefa.Finalizado;
            }
            else
            {
                Status = EnumStatusTarefa.Pendente;
            }
        }

    
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TrilhaApiDesafio.Models;
using TrilhaApiDesafio.Context;

namespace TrilhaApiDesafio.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        

        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrilhaApiDesafio.Context;
using TrilhaApiDesafio.Models;

namespace TrilhaApiDesafio.Controllers
{
    public class TarefaController : Controller
    {
        private readonly AgendaContext _context;
        

        public TarefaController(AgendaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var tarefas = _context.Tarefas.ToList();

            if(tarefas.Count == 0) return RedirectToAction(nameof(SemTarefas));

            return View(tarefas);
        }

        public IActionResult SemTarefas()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Tarefa tarefa)
        {
            if(ModelState.IsValid)
            {
                _context.Tarefas.Add(tarefa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        public IActionResult Editar(int id)
        {

            var tarefa = _context.Tarefas.Find(id);

            if(tarefa == null) return RedirectToAction(nameof(Index));

            return View(tarefa);
        }

        [HttpPost]
        public IActionResult Editar(Tarefa tarefa)
        {
            if(ModelState.IsValid)
            {
                _context.Update(tarefa);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Deletar(int id)
        {
            var tarefa = _context.Tarefas.Find(id);

            if(tarefa == null) return RedirectToAction(nameof(Index));

            return View(tarefa);
        }

        [HttpPost]
        public IActionResult Deletar(Tarefa tarefa)
        {
            if(ModelState.IsValid)
            {
                _context.Tarefas.Remove(tarefa);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public IActionResult AlterarStatus(int id)
        {

            var tarefa = _context.Tarefas.Find(id);
            tarefa.ToggleStatus();
            _context.Tarefas.Update(tarefa);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Buscar()
        {
            return View();
        }

        public IActionResult ObterPorId()
        {
            return View();
        }

        public IActionResult TarefaPorId(int id)
        {
            var tarefa = _context.Tarefas.Find(id);

            List<Tarefa> tarefas = new List<Tarefa>();

            tarefas.Add(tarefa);

            return View("Detalhes", tarefas);

        }

        public IActionResult ObterPorTitulo()
        {
            return View();
        }

        public IActionResult TarefaPorTitulo(string titulo)
        {

            var tarefas = _context.Tarefas.Where(tarefa => tarefa.Titulo.Contains(titulo)).ToList();


            return View("Detalhes", tarefas);
        }

        public IActionResult ObterPorData()
        {
            return View();
        }


        public IActionResult TarefaPorData(DateTime data)
        {

            var tarefas = _context.Tarefas.Where(tarefa => tarefa.Data.Date == data.Date).ToList();

            return View("Detalhes", tarefas);
        }

        public IActionResult ObterPorStatus()
        {
            return View();
        }

        public IActionResult TarefaPorStatus(EnumStatusTarefa status)
        {
            var tarefas = _context.Tarefas.Where(tarefa => tarefa.Status == status).ToList();
            
            return View("Detalhes", tarefas);
        }
        
    }
}

Views/Home/Index.cshtml
@model IEnumerable<TrilhaApiDesafio.Models.Tarefa>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
</div>

<div class="d-flex m-auto flex-column col-sm-3 btn-group-vertical " role="group">
    <a asp-controller="Tarefa" asp-action="Index" class="btn btn-info p-4">Listar Tarefas</a>
    <a asp-controller="Tarefa" asp-action="Criar" class="btn btn-success p-4">Adicionar Tarefa</a>
    <a asp-controller="Tarefa" asp-action="Buscar" class="btn btn-secondary p-4">Buscar Tarefas</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo Asp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrilhaApiDesafio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand ms-4" asp-area="" asp-controller="Home" asp-action="Index">ToDo Asp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TrilhaApiDesafio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tarefa/Buscar.cshtml
<div class="container">
    <div class="btn-group-vertical">
        <a asp-action="Index">Obter Todos</a>
        <a asp-action="ObterPorId">Buscar por Id</a>
        <a asp-action="ObterPorTitulo">Buscar por Titulo</a>
        <a asp-action="ObterPorData">Buscar por Data</a>
        <a asp-action="ObterPorStatus">Buscar por Status</a>
    </div>
</div>

Views/Tarefa/Criar.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="text-center row container-fluid">
    <form asp-action="Criar">
        <div class="input-group-prepend d-flex flex-column flex-sm-row align-items-center">
            <div class="input-group p-4">
                <label asp-for="Titulo" class="input-group-text"></label>
                <input asp-for="Titulo" type="text" class="form-control ">
            </div>
            <div class="input-group p-4">
                <label asp-for="Descricao" class="input-group-text"></label>
                <input asp-for="Descricao" type="text" class="form-control" rows="1" cols="45">
            </div>
            <div class="input-group p-4">
                <label asp-for="Data" class="input-group-text"></label>
                <input asp-for="Data" type="datetime-local" class="form-control">
            </div>
        </div>
        <div class="p-4 input-group-append">
            <input type="submit" value="Criar" class="btn btn-primary">
        </div>
    </form>
</div>

Views/Tarefa/Deletar.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="container">
    <h4 class="text-danger">Deseja realmente deletar esta tarefa?</h4>
    <ul class="list-group">
        <li class="list-group-item d-flex align-items-end"> 
            <p class="col-sm-2">
                <b>Nome: </b>@Html.DisplayFor(model => model.Titulo)
            </p>
            <p class="col-sm">
                <b>Descrição: </b>@Html.DisplayFor(model => model.Descricao)
            </p>
            <p class="col-sm-3">
                <b>Data: </b>@Html.DisplayFor(model => model.Data)
            </p>
            <p class="col-sm-2">
                <b>Status: </b>@Html.DisplayFor(model => model.Status)
            </p>
            <form asp-action="Deletar" class="btn-group col-sm-2 align-self-center">
                <input type="submit" value="Deletar" class="btn btn-danger">
            </form>
        </li>
    </ul>
</div>

Views/Tarefa/Detalhe.cshtml
@model TrilhaApiDesafio.Models.Tarefa
<ul>
        <li class="list-group-item d-flex flex-column flex-sm-row"> 
            <div class="container d-flex flex-wrap align-self-center">
                <p class="col-sm">
                    <b>Nome: </b>@Html.DisplayFor(model => model.Titulo)
                </p>
                <p class="col-sm-5">
                    <b>Descrição: </b>@Html.DisplayFor(model => model.Descricao)
                </p>
                <p class="col-sm">
                    <b>Data: </b>@Html.DisplayFor(model => model.Data)
                </p>
                <p class="col-sm">
                    <b>Status: </b>@Html.DisplayFor(model => model.Status)
                </p>
            </div>
            <div>
                <form asp-action="AlterarStatus" asp-route-id="@Model.Id" class="btn-group-vertical btn-group-sm align-self-center d-none d-sm-block">
                    <input type="submit" value="AlterarStatus" class="btn btn-primary">
                    <a asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-success">Editar</a>
                    <a asp-action="Deletar" asp-route-id="@Model.Id" class="btn btn-danger">Deletar</a>
                </form>
            </div>
            <div>
                <form asp-action="AlterarStatus" asp-route-id="@Model.Id" class="btn-group btn-group-sm align-self-center d-block d-sm-none">
                    <input type="submit" value="AlterarStatus" class="btn btn-primary">
                    <a asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-success">Editar</a>
                    <a asp-action="Deletar" asp-route-id="@Model.Id" class="btn btn-danger">Deletar</a>
                </form>
            </div>
        </li>
    </ul>

Views/Tarefa/Detalhes.cshtml
@model IEnumerable<TrilhaApiDesafio.Models.Tarefa>


<div class="container-fluid">
    <div class="row">
        <ul class="list-group">
            @foreach (var item in Model)
            {
                <li class="list-group-item d-flex flex-column flex-sm-row"> 
                    <div class="container d-flex flex-wrap align-self-center">
                        <p class="col-sm">
                            <b>Nome: </b>@Html.DisplayFor(model => item.Titulo)
                        </p>
                        <p class="col-sm-5">
                            <b>Descrição: </b>@Html.DisplayFor(model => item.Descricao)
                        </p>
                        <p class="col-sm">
                            <b>Data: </b>@Html.DisplayFor(model => item.Data)
                        </p>
                        <p class="col-sm">
                            <b>Status: </b>@Html.DisplayFor(model => item.Status)
                        </p>
                    </div>
                    <div>
                        <form asp-action="AlterarStatus" asp-route-id="@item.Id" class="btn-group-vertical btn-group-sm align-self-center d-none d-sm-block">
                            <input type="submit" value="AlterarStatus" class="btn btn-primary">
                            <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-success">Editar</a>
                            <a asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger">Deletar</a>
                        </form>
                    </div>
                    <div>
                        <form asp-action="AlterarStatus" asp-route-id="@item.Id" class="btn-group btn-group-sm align-self-center d-block d-sm-none">
                            <input type="submit" value="AlterarStatus" class="btn btn-primary">
                            <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-success">Editar</a>
                            <a asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger">Deletar</a>
                        </form>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

Views/Tarefa/Editar.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="m-auto">
        <form asp-action="Editar">
            <div class="d-flex justify-content">
                <div class="input-group">
                    <label asp-for="Titulo" class="input-group-text"></label>
                    <input asp-for="Titulo" type="text" class="form-control ">
                </div>
                <div class="input-group">
                    <label asp-for="Descricao" class="input-group-text"></label>
                    <input asp-for="Descricao" type="text" class="form-control">
                </div>
                <div class="input-group">
                    <label asp-for="Data" class="input-group-text"></label>
                    <input asp-for="Data" type="datetime-local" class="form-control">
                </div>
                <div class="input-group ml-auto">
                    <input type="submit" value="Editar" class="btn btn-primary">
                </div>
            </div>
        </form>
</div>

Views/Tarefa/Index.cshtml
@model IEnumerable<TrilhaApiDesafio.Models.Tarefa>


<div class="container-fluid">
    <div class="row">
        <ul class="list-group">
            @foreach (var item in Model)
            {
                <li class="list-group-item d-flex flex-column flex-sm-row"> 
                    <div class="container d-flex flex-wrap align-self-center">
                        <p class="col-sm">
                            <b>Nome: </b>@Html.DisplayFor(model => item.Titulo)
                        </p>
                        <p class="col-sm-5 tarefa-descricao">
                            <b>Descrição: </b>@Html.DisplayFor(model => item.Descricao)
                        </p>
                        <p class="col-sm">
                            <b>Data: </b>@Html.DisplayFor(model => item.Data)
                        </p>
                        <p class="col-sm status">
                            <b>Status: </b>@Html.DisplayFor(model => item.Status)
                        </p>
                    </div>
                    <div>
                        <form asp-action="AlterarStatus" asp-route-id="@item.Id" class="btn-group-vertical btn-group-sm align-self-center d-none d-sm-block">
                            <input type="submit" value="AlterarStatus" class="btn btn-primary toggle-status">
                            <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-success">Editar</a>
                            <a asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger">Deletar</a>
                        </form>
                    </div>
                    <div>
                        <form asp-action="AlterarStatus" asp-route-id="@item.Id" class="btn-group btn-group-sm align-self-center d-block d-sm-none">
                            <input type="submit" value="AlterarStatus" class="btn btn-primary">
                            <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-success">Editar</a>
                            <a asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger">Deletar</a>
                        </form>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

Views/Tarefa/ObterPorData.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="container col-sm-6">
    <form asp-action="TarefaPorData" class="input-group">
        <label class="input-group-text">Data</label>
        <input asp-for="Data"  type="date" class="form-control">
        <div class="input-group-prepend">
            <input  type="submit" class="btn btn-outline-primary" value="Buscar"/>
        </div>
    </form>
</div>

Views/Tarefa/ObterPorId.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="container col-sm-6">
    <form asp-action="TarefaPorId" class="input-group">
        <label class="input-group-text">Id</label>
        <input asp-for="Id"  type="text" class="form-control">
        <div class="input-group-prepend">
            <input  type="submit" class="btn btn-outline-primary" value="Buscar"/>
        </div>
    </form>
</div>

Views/Tarefa/ObterPorStatus.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="container col-sm-6">
    <form asp-action="TarefaPorStatus" class="input-group">
        <label class="input-group-text">Status</label>
        <select asp-for="Status"  type="date" class="form-control">
            <option value="Pendente">Pendente</option>
            <option value="Finalizado">Finalizado</option>
        </select>
        <div class="input-group-prepend">
            <input  type="submit" class="btn btn-outline-primary" value="Buscar"/>
        </div>
    </form>
</div>

Views/Tarefa/ObterPorTitulo.cshtml
@model TrilhaApiDesafio.Models.Tarefa

<div class="container col-sm-6">
    <form asp-action="TarefaPorTitulo" class="input-group">
        <label class="input-group-text">Titulo</label>
        <input asp-for="Titulo"  type="text" class="form-control">
        <div class="input-group-prepend">
            <input  type="submit" class="btn btn-outline-primary" value="Buscar"/>
        </div>
    </form>
</div>

Views/Tarefa/SemTarefas.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="container-fluid">

<div class="text-center">
    <h4 class="">Nenhuma Tarefa Pendente!</h4>
</div>

<div class="text-center">
    <button class="btn btn-success">
    <a class="text-white" asp-controller="Tarefa" asp-action="Criar">Adicionar Tarefa</a>
    </button>
</div>

</div>